services:
  db:
    container_name: ara-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cooperative
      POSTGRES_DB: ara-db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ara-db"]
      interval: 10s
      timeout: 5s
  
  api:
    container_name: ara-api
    volumes:
      - ./:/app # mount the current directory to /app
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --location 'http://localhost:5001/api/v1/health'"]  
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 40s 

  cache:
    container_name: ara-redis
    image: redis:8.0.3-alpine3.21
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    